[[rust_agents]]
= Rust

== What?

Executable `Subgraphs` are defined as a network of `Agents`, which exchange typed data across predefined connections by message passing, where the connections are specified externally to the processes. These `Agents`  can be reconnected endlessly to form different executable `Subgraphs` without having to be changed internally.

== Why?

Functions in a programming language should be placed in a content addressable store, this is the horizontal plane. The vertical plane should be constructed using unique addresses into this content addressable store, critically each address should solve a single problem, and may do so by referencing multiple other unique addresses in the content addressable store. Users must not have knowledge of these unique addresses but a translation process should occur from a human readable name to a universally unique address. Read http://erlang.org/pipermail/erlang-questions/2011-May/058768.html[more] about the problem.

Nix gives us the content addressable store which allows for `reproducibility`, and these `agents` give us `reusablility`. The combination is particularly potent form of programming.

Once you have the above, you have truly reusable and reproducible functions. Fractalide nodes are just this, and it makes the below so much easier to achieve:

[source]
----
* Open source collaboration
* Open peer review of nodes
* Nice clean reusable nodes
* Reproducible applications
----

== Who?

Typically programmers will develop `Agents`. They specialize in making `Agents` as efficient and reusable as possible, while people who focus on the Science give the requirements and use the `Subgraphs`. Just as a hammer is designed to be reused, so `Subgraphs` and `Agents` should be designed for reuse.

== Where?

The `Agents` are found in this `nodes` directory, or the `nodes` directory of a <<fractal,fractal>>.

[source, sh]
----
processchunk
├── default.nix
├── agg_chunk_triples
│   ├── default.nix <---
│   └── lib.rs
├── convert_json_vector
│   ├── default.nix <---
│   └── lib.rs
├── extract_keyvalue
│   ├── default.nix <---
│   └── lib.rs
├── file_open
│   ├── default.nix <---
│   └── lib.rs
└── iterate_paths
    ├── default.nix <---
    └── lib.rs
----

Typically when you see a `lib.rs` in the same directory as a `default.nix` you know it's an `Agent`.

== How?

An `Agent` consists of two parts:

* a `nix` `default.nix` file that sets up an environment to satisfy `rustc`.
* a `rust` `lib.rs` file implements your `agent`.

=== The `agent` Nix function.

The `agent` function in the `default.nix` requires you make decisions about three types of dependencies.

* What `edges` are needed?
* What `mods` from https://crates.io[crates.io] are needed?
* What `osdeps` or `operating system level dependencies` are needed?

[source, nix, subs="none"]
----
{ agent, edges, mods, pkgs }:

agent {
  src = ./.;
  edges = with edges.rs; [ ];
  mods = with mods.rs; [ rustfbp ];
  osdeps = with pkgs; [];
}

----

* The `{ agent, edges, mods, pkgs }:` lambda imports: The `edges` attribute which consists of every `edge` available on the system. The `mods` attribute set consists of every `crate` on https://crates.io. Lastly the `pkgs` pulls in every third party package available on NixOS, here's the whole http://nixos.org/nixos/packages.html[list].
* The `agent` function builds the rust `lib.rs` source code, and accepts these arguments:
** The `src` attribute is used to derive an `Agent` name based on location in the directory hierarchy.
** The `edges` lazily compiles schema and composite schema ensuring their availability. Sometimes when the types are rust primatives there doesn't need to be a type in the square brackets. Otherwise the type is derived from the `edges` directory tree.
** The `mods` specifies exactly which `mods` are needed in scope.
** The `osdeps` specifies exactly which `pkgs`, or third party `operating system level libraries` such as `openssl` needed in scope.

Only specified dependencies and their transitive dependencies will be pulled into scope once the `agent` compilation starts.

This is the output of the above ``agent``'s compilation:

[source, sh]
----
/nix/store/dp8s7d3p80q18a3pf2b4dk0bi4f856f8-maths_boolean_nand
└── lib
    └── libagent.so
----

=== The `agent!` Rust macro

This is the heart of `Fractalide`. Everything revolves around this `API`. The below is an implementation of the `${maths_boolean_nand}` `agent` seen earlier.

[source, rust]
----
#[macro_use]
extern crate rustfbp;

agent! {
  input(a: bool, b: bool),
  output(output: bool),
  fn run(&mut self) -> Result<Signal> {
    let a = self.input.a.recv()?;
    let b = self.input.b.recv()?;
    let res = ! (a && b);
    self.output.output.send(res)?;
    Ok(End)
  }
}

----

An explanation of each of the items should be given.
All expresions are optional except for the `run` function.

==== `input`:

[source, rust]
----
#[macro_use]
extern crate rustfbp;

agent! {
  input(input_name: bool),
  fn run(&mut self) -> Result<Signal> {
    let msg = self.input.input_name.recv()?;
    Ok(End)
  }
}
----

The `input` port, is a bounded buffer simple input channel rust typed data as messages.

==== `inarr`:

[source, rust]
----
#[macro_use]
extern crate rustfbp;

agent! {
  inarr(input_array_name: i32),
  fn run(&mut self) -> Result<Signal> {
    let mut sum = 0;
    for (_id, elem) in &self.inarr.input_array_name {
      sum += elem.recv()?;
    }
    Ok(End)
  }
}
----

The `inarr` is an input array port, which consists of multiple elements of a port.
They are used when the `Subgraph` developer needs multiple elements of a port, for example an `adder` has multiple input elements. This `adder` `agent` may be used in many scenarios where the amount of inputs are unknown at `agent development time`.

==== `output`:

[source, rust]
----
#[macro_use]
extern crate rustfbp;

agent! {
  output(output_name: prim_bool),
  fn run(&mut self) -> Result<Signal> {
    self.output.output_name.send(true)?;
    Ok(End)
  }
}
----

The humble simple output port. It doesn't have elements and is fixed at `subgraph development time`.

==== `outarr`:

[source, rust]
----
#[macro_use]
extern crate rustfbp;

agent! {
  outarr(out_array_name: bool),
  fn run(&mut self) -> Result<Signal> {
    for p in self.outarr.out_array_name.elements()? {
      self.outarr.out_array_name.send(true)?;
    }
    Ok(End)
  }
}
----

The `outarr` port is an `output array port`. It contains elements which may be expanded at `subgraph development time`.

==== `option`:

[source, rust]
----
agent! {
  option(bool),
  fn run(&mut self) -> Result<Signal> {
    let mut opt = self.option.recv();
    // use opt to configure something
    Ok(End)
  }
}
----

The `option` port gives the `subgraph` developer a way to send in parameters such as a connection string and the message will not be consumed and thrown away, that message may be read on every function run. Whereas other ports will consume and throw away the message.

==== `accumulator`:

[source, rust]
----
agent! {
  accumulator(prim_bool),
  fn run(&mut self) -> Result<Signal> {
    let acc = self.ports.accumulator.recv()?;
    // use the accumulator to start accumulating something.
    Ok(End)
  }
}
----

The `accumulator` gives the `subgraph` developer a way to start counting at a certain number. It's a way of passing in initial state.

==== `run`:

This function does the actual processing and is the only mandatory expression of this macro. You've seen many examples already.
