#lang racket

(require fractalide/modules/rkt/rkt-fbp/graph)

(define-graph
  (node "not0" ${math.not})
  (node "not1" ${math.not})
  (node "not2" ${math.not})
  (node "not3" ${math.not})
  (node "not4" ${math.not})
  (node "not5" ${math.not})
  (node "not6" ${math.not})
  (node "not7" ${math.not})
  (node "not8" ${math.not})
  (node "not9" ${math.not})
  (node "not10" ${math.not})
  (node "not11" ${math.not})
  (node "not12" ${math.not})
  (node "not13" ${math.not})
  (node "not14" ${math.not})
  (node "not15" ${math.not})
  (edge-in "in0" "not0" "in")
  (edge-in "in1" "not1" "in")
  (edge-in "in2" "not2" "in")
  (edge-in "in3" "not3" "in")
  (edge-in "in4" "not4" "in")
  (edge-in "in5" "not5" "in")
  (edge-in "in6" "not6" "in")
  (edge-in "in7" "not7" "in")
  (edge-in "in8" "not8" "in")
  (edge-in "in9" "not9" "in")
  (edge-in "in10" "not10" "in")
  (edge-in "in11" "not11" "in")
  (edge-in "in12" "not12" "in")
  (edge-in "in13" "not13" "in")
  (edge-in "in14" "not14" "in")
  (edge-in "in15" "not15" "in")
  (edge-out "not0" "out" "out0")
  (edge-out "not1" "out" "out1")
  (edge-out "not2" "out" "out2")
  (edge-out "not3" "out" "out3")
  (edge-out "not4" "out" "out4")
  (edge-out "not5" "out" "out5")
  (edge-out "not6" "out" "out6")
  (edge-out "not7" "out" "out7")
  (edge-out "not8" "out" "out8")
  (edge-out "not9" "out" "out9")
  (edge-out "not10" "out" "out10")
  (edge-out "not11" "out" "out11")
  (edge-out "not12" "out" "out12")
  (edge-out "not13" "out" "out13")
  (edge-out "not14" "out" "out14")
  (edge-out "not15" "out" "out15")
  )
