# Generated by carnix 0.8.11: carnix generate-nix --src ./.
{ lib, buildPlatform, buildRustCrate, buildRustCrateHelpers, cratesIO, fetchgit }:
with buildRustCrateHelpers;
let inherit (lib.lists) fold;
    inherit (lib.attrsets) recursiveUpdate;
in
let crates = cratesIO // rec {
  crates.all_crates."1.1.1" = deps: { features?(features_.all_crates."1.1.1" deps {}) }: buildRustCrate {
    crateName = "all_crates";
    version = "1.1.1";
    authors = [ ];
    src = exclude [ ".git" "target" ] ./.;
    dependencies = mapFeatures features ([
      (crates."cardano"."${deps."all_crates"."1.1.1"."cardano"}" deps)
      (crates."cardano_storage"."${deps."all_crates"."1.1.1"."cardano_storage"}" deps)
      (cratesIO.crates."env_logger"."${deps."all_crates"."1.1.1"."env_logger"}" deps)
      (crates."exe_common"."${deps."all_crates"."1.1.1"."exe_common"}" deps)
      (crates."generate_msg"."${deps."all_crates"."1.1.1"."generate_msg"}" deps)
      (cratesIO.crates."log"."${deps."all_crates"."1.1.1"."log"}" deps)
      (cratesIO.crates."nom"."${deps."all_crates"."1.1.1"."nom"}" deps)
      (crates."protocol"."${deps."all_crates"."1.1.1"."protocol"}" deps)
      (crates."rustfbp"."${deps."all_crates"."1.1.1"."rustfbp"}" deps)
      (crates."storage_units"."${deps."all_crates"."1.1.1"."storage_units"}" deps)
    ]);
  };
  features_.all_crates."1.1.1" = deps: f: updateFeatures f (rec {
    all_crates."1.1.1".default = (f.all_crates."1.1.1".default or true);
    cardano."${deps.all_crates."1.1.1".cardano}".default = true;
    cardano_storage."${deps.all_crates."1.1.1".cardano_storage}".default = true;
    env_logger."${deps.all_crates."1.1.1".env_logger}".default = true;
    exe_common."${deps.all_crates."1.1.1".exe_common}".default = true;
    generate_msg."${deps.all_crates."1.1.1".generate_msg}".default = true;
    log."${deps.all_crates."1.1.1".log}".default = true;
    nom."${deps.all_crates."1.1.1".nom}".default = true;
    protocol."${deps.all_crates."1.1.1".protocol}".default = true;
    rustfbp."${deps.all_crates."1.1.1".rustfbp}".default = true;
    storage_units."${deps.all_crates."1.1.1".storage_units}".default = true;
  }) [
    (features_.cardano."${deps."all_crates"."1.1.1"."cardano"}" deps)
    (features_.cardano_storage."${deps."all_crates"."1.1.1"."cardano_storage"}" deps)
    (cratesIO.features_.env_logger."${deps."all_crates"."1.1.1"."env_logger"}" deps)
    (features_.exe_common."${deps."all_crates"."1.1.1"."exe_common"}" deps)
    (features_.generate_msg."${deps."all_crates"."1.1.1"."generate_msg"}" deps)
    (cratesIO.features_.log."${deps."all_crates"."1.1.1"."log"}" deps)
    (cratesIO.features_.nom."${deps."all_crates"."1.1.1"."nom"}" deps)
    (features_.protocol."${deps."all_crates"."1.1.1"."protocol"}" deps)
    (features_.rustfbp."${deps."all_crates"."1.1.1"."rustfbp"}" deps)
    (features_.storage_units."${deps."all_crates"."1.1.1"."storage_units"}" deps)
  ];


  crates.cardano."0.1.0" = deps: { features?(features_.cardano."0.1.0" deps {}) }: buildRustCrate {
    crateName = "cardano";
    version = "0.1.0";
    authors = [ "Vincent Hanquez <vincent.hanquez@iohk.io>" "Nicolas Di Prima <nicolas.diprima@iohk.io>" ];
    src = exclude [ ".git" "target" ] /nix/store/lk795k7bz6d9b9bhax09dhc5wpddmna5-rust-cardano-4403a9f/cardano;
    dependencies = mapFeatures features ([
      (cratesIO.crates."cbor_event"."${deps."cardano"."0.1.0"."cbor_event"}" deps)
      (cratesIO.crates."cryptoxide"."${deps."cardano"."0.1.0"."cryptoxide"}" deps)
    ]
      ++ (if features.cardano."0.1.0".serde or false then [ (cratesIO.crates.serde."1.0.80" deps) ] else [])
      ++ (if features.cardano."0.1.0".serde_derive or false then [ (cratesIO.crates.serde_derive."1.0.80" deps) ] else []));
    features = mkFeatures (features."cardano"."0.1.0" or {});
  };
  features_.cardano."0.1.0" = deps: f: updateFeatures f (rec {
    cardano = fold recursiveUpdate {} [
      { "0.1.0".default = (f.cardano."0.1.0".default or true); }
      { "0.1.0".serde =
        (f.cardano."0.1.0".serde or false) ||
        (f.cardano."0.1.0".generic-serialization or false) ||
        (cardano."0.1.0"."generic-serialization" or false); }
      { "0.1.0".serde_derive =
        (f.cardano."0.1.0".serde_derive or false) ||
        (f.cardano."0.1.0".generic-serialization or false) ||
        (cardano."0.1.0"."generic-serialization" or false); }
    ];
    cbor_event."${deps.cardano."0.1.0".cbor_event}".default = true;
    cryptoxide."${deps.cardano."0.1.0".cryptoxide}".default = true;
    serde."${deps.cardano."0.1.0".serde}".default = true;
    serde_derive."${deps.cardano."0.1.0".serde_derive}".default = true;
  }) [
    (cratesIO.features_.cbor_event."${deps."cardano"."0.1.0"."cbor_event"}" deps)
    (cratesIO.features_.cryptoxide."${deps."cardano"."0.1.0"."cryptoxide"}" deps)
    (cratesIO.features_.serde."${deps."cardano"."0.1.0"."serde"}" deps)
    (cratesIO.features_.serde_derive."${deps."cardano"."0.1.0"."serde_derive"}" deps)
  ];


  crates.cardano_storage."0.1.0" = deps: { features?(features_.cardano_storage."0.1.0" deps {}) }: buildRustCrate {
    crateName = "cardano-storage";
    version = "0.1.0";
    authors = [ "Vincent Hanquez <vincent.hanquez@iohk.io>" "Nicolas Di Prima <nicolas.diprima@iohk.io>" ];
    src = exclude [ ".git" "target" ] /nix/store/lk795k7bz6d9b9bhax09dhc5wpddmna5-rust-cardano-4403a9f/storage;
    dependencies = mapFeatures features ([
      (crates."cardano"."${deps."cardano_storage"."0.1.0"."cardano"}" deps)
      (cratesIO.crates."cbor_event"."${deps."cardano_storage"."0.1.0"."cbor_event"}" deps)
      (cratesIO.crates."log"."${deps."cardano_storage"."0.1.0"."log"}" deps)
      (cratesIO.crates."rand"."${deps."cardano_storage"."0.1.0"."rand"}" deps)
      (crates."storage_units"."${deps."cardano_storage"."0.1.0"."storage_units"}" deps)
    ]);
  };
  features_.cardano_storage."0.1.0" = deps: f: updateFeatures f (rec {
    cardano."${deps.cardano_storage."0.1.0".cardano}".default = true;
    cardano_storage."0.1.0".default = (f.cardano_storage."0.1.0".default or true);
    cbor_event."${deps.cardano_storage."0.1.0".cbor_event}".default = true;
    log."${deps.cardano_storage."0.1.0".log}".default = true;
    rand."${deps.cardano_storage."0.1.0".rand}".default = true;
    storage_units."${deps.cardano_storage."0.1.0".storage_units}".default = true;
  }) [
    (features_.cardano."${deps."cardano_storage"."0.1.0"."cardano"}" deps)
    (cratesIO.features_.cbor_event."${deps."cardano_storage"."0.1.0"."cbor_event"}" deps)
    (cratesIO.features_.log."${deps."cardano_storage"."0.1.0"."log"}" deps)
    (cratesIO.features_.rand."${deps."cardano_storage"."0.1.0"."rand"}" deps)
    (features_.storage_units."${deps."cardano_storage"."0.1.0"."storage_units"}" deps)
  ];


  crates.exe_common."0.1.0" = deps: { features?(features_.exe_common."0.1.0" deps {}) }: buildRustCrate {
    crateName = "exe-common";
    version = "0.1.0";
    authors = [ "Vincent Hanquez <vincent.hanquez@iohk.io>" "Nicolas Di Prima <nicolas.diprima@iohk.io>" ];
    src = exclude [ ".git" "target" ] /nix/store/lk795k7bz6d9b9bhax09dhc5wpddmna5-rust-cardano-4403a9f/exe-common;
    dependencies = mapFeatures features ([
      (crates."cardano"."${deps."exe_common"."0.1.0"."cardano"}" deps)
      (crates."cardano_storage"."${deps."exe_common"."0.1.0"."cardano_storage"}" deps)
      (cratesIO.crates."cbor_event"."${deps."exe_common"."0.1.0"."cbor_event"}" deps)
      (cratesIO.crates."futures"."${deps."exe_common"."0.1.0"."futures"}" deps)
      (cratesIO.crates."hyper"."${deps."exe_common"."0.1.0"."hyper"}" deps)
      (cratesIO.crates."log"."${deps."exe_common"."0.1.0"."log"}" deps)
      (crates."protocol"."${deps."exe_common"."0.1.0"."protocol"}" deps)
      (cratesIO.crates."rand"."${deps."exe_common"."0.1.0"."rand"}" deps)
      (cratesIO.crates."serde"."${deps."exe_common"."0.1.0"."serde"}" deps)
      (cratesIO.crates."serde_derive"."${deps."exe_common"."0.1.0"."serde_derive"}" deps)
      (cratesIO.crates."serde_yaml"."${deps."exe_common"."0.1.0"."serde_yaml"}" deps)
      (crates."storage_units"."${deps."exe_common"."0.1.0"."storage_units"}" deps)
      (cratesIO.crates."tokio_core"."${deps."exe_common"."0.1.0"."tokio_core"}" deps)
    ]);
  };
  features_.exe_common."0.1.0" = deps: f: updateFeatures f (rec {
    cardano = fold recursiveUpdate {} [
      { "${deps.exe_common."0.1.0".cardano}"."generic-serialization" = true; }
      { "${deps.exe_common."0.1.0".cardano}".default = true; }
    ];
    cardano_storage."${deps.exe_common."0.1.0".cardano_storage}".default = true;
    cbor_event."${deps.exe_common."0.1.0".cbor_event}".default = true;
    exe_common."0.1.0".default = (f.exe_common."0.1.0".default or true);
    futures."${deps.exe_common."0.1.0".futures}".default = true;
    hyper."${deps.exe_common."0.1.0".hyper}".default = true;
    log."${deps.exe_common."0.1.0".log}".default = true;
    protocol."${deps.exe_common."0.1.0".protocol}".default = true;
    rand."${deps.exe_common."0.1.0".rand}".default = true;
    serde."${deps.exe_common."0.1.0".serde}".default = true;
    serde_derive."${deps.exe_common."0.1.0".serde_derive}".default = true;
    serde_yaml."${deps.exe_common."0.1.0".serde_yaml}".default = true;
    storage_units."${deps.exe_common."0.1.0".storage_units}".default = true;
    tokio_core."${deps.exe_common."0.1.0".tokio_core}".default = true;
  }) [
    (features_.cardano."${deps."exe_common"."0.1.0"."cardano"}" deps)
    (features_.cardano_storage."${deps."exe_common"."0.1.0"."cardano_storage"}" deps)
    (cratesIO.features_.cbor_event."${deps."exe_common"."0.1.0"."cbor_event"}" deps)
    (cratesIO.features_.futures."${deps."exe_common"."0.1.0"."futures"}" deps)
    (cratesIO.features_.hyper."${deps."exe_common"."0.1.0"."hyper"}" deps)
    (cratesIO.features_.log."${deps."exe_common"."0.1.0"."log"}" deps)
    (features_.protocol."${deps."exe_common"."0.1.0"."protocol"}" deps)
    (cratesIO.features_.rand."${deps."exe_common"."0.1.0"."rand"}" deps)
    (cratesIO.features_.serde."${deps."exe_common"."0.1.0"."serde"}" deps)
    (cratesIO.features_.serde_derive."${deps."exe_common"."0.1.0"."serde_derive"}" deps)
    (cratesIO.features_.serde_yaml."${deps."exe_common"."0.1.0"."serde_yaml"}" deps)
    (features_.storage_units."${deps."exe_common"."0.1.0"."storage_units"}" deps)
    (cratesIO.features_.tokio_core."${deps."exe_common"."0.1.0"."tokio_core"}" deps)
  ];


  crates.generate_msg."0.1.0" = deps: { features?(features_.generate_msg."0.1.0" deps {}) }: buildRustCrate {
    crateName = "generate_msg";
    version = "0.1.0";
    authors = [ "pe@pijul.org <pe@pijul.org>" ];
    src = exclude [ ".git" "target" ] /nix/store/9d4dmyh3pb2yqpw4hv7yvmsw3a8qsn1s-generate-msg;
    dependencies = mapFeatures features ([
      (cratesIO.crates."syn"."${deps."generate_msg"."0.1.0"."syn"}" deps)
    ]);
  };
  features_.generate_msg."0.1.0" = deps: f: updateFeatures f (rec {
    generate_msg."0.1.0".default = (f.generate_msg."0.1.0".default or true);
    syn = fold recursiveUpdate {} [
      { "${deps.generate_msg."0.1.0".syn}"."full" = true; }
      { "${deps.generate_msg."0.1.0".syn}".default = true; }
    ];
  }) [
    (cratesIO.features_.syn."${deps."generate_msg"."0.1.0"."syn"}" deps)
  ];


  crates.protocol."0.1.0" = deps: { features?(features_.protocol."0.1.0" deps {}) }: buildRustCrate {
    crateName = "protocol";
    version = "0.1.0";
    authors = [ "Vincent Hanquez <vincent.hanquez@iohk.io>" "Nicolas Di Prima <nicolas.diprima@iohk.io>" ];
    src = exclude [ ".git" "target" ] /nix/store/lk795k7bz6d9b9bhax09dhc5wpddmna5-rust-cardano-4403a9f/exe-common/../protocol;
    dependencies = mapFeatures features ([
      (crates."cardano"."${deps."protocol"."0.1.0"."cardano"}" deps)
      (cratesIO.crates."cbor_event"."${deps."protocol"."0.1.0"."cbor_event"}" deps)
      (cratesIO.crates."log"."${deps."protocol"."0.1.0"."log"}" deps)
    ]);
  };
  features_.protocol."0.1.0" = deps: f: updateFeatures f (rec {
    cardano."${deps.protocol."0.1.0".cardano}".default = true;
    cbor_event."${deps.protocol."0.1.0".cbor_event}".default = true;
    log."${deps.protocol."0.1.0".log}".default = true;
    protocol."0.1.0".default = (f.protocol."0.1.0".default or true);
  }) [
    (features_.cardano."${deps."protocol"."0.1.0"."cardano"}" deps)
    (cratesIO.features_.cbor_event."${deps."protocol"."0.1.0"."cbor_event"}" deps)
    (cratesIO.features_.log."${deps."protocol"."0.1.0"."log"}" deps)
  ];


  crates.rustfbp."0.3.34" = deps: { features?(features_.rustfbp."0.3.34" deps {}) }: buildRustCrate {
    crateName = "rustfbp";
    version = "0.3.34";
    authors = [ "Denis Michiels <dmichiels@gmail.com>" "Stewart Mackenzie <setori88@gmail.com>" ];
    src = exclude [ ".git" "target" ] /nix/store/g4sjyz34avlm5hnlv0y4bm1fhqvyyvrc-rustfbp;
    dependencies = mapFeatures features ([
      (cratesIO.crates."env_logger"."${deps."rustfbp"."0.3.34"."env_logger"}" deps)
      (cratesIO.crates."libloading"."${deps."rustfbp"."0.3.34"."libloading"}" deps)
      (cratesIO.crates."threadpool"."${deps."rustfbp"."0.3.34"."threadpool"}" deps)
    ]);
  };
  features_.rustfbp."0.3.34" = deps: f: updateFeatures f (rec {
    env_logger."${deps.rustfbp."0.3.34".env_logger}".default = true;
    libloading."${deps.rustfbp."0.3.34".libloading}".default = true;
    rustfbp."0.3.34".default = (f.rustfbp."0.3.34".default or true);
    threadpool."${deps.rustfbp."0.3.34".threadpool}".default = true;
  }) [
    (cratesIO.features_.env_logger."${deps."rustfbp"."0.3.34"."env_logger"}" deps)
    (cratesIO.features_.libloading."${deps."rustfbp"."0.3.34"."libloading"}" deps)
    (cratesIO.features_.threadpool."${deps."rustfbp"."0.3.34"."threadpool"}" deps)
  ];


  crates.storage_units."0.1.0" = deps: { features?(features_.storage_units."0.1.0" deps {}) }: buildRustCrate {
    crateName = "storage-units";
    version = "0.1.0";
    authors = [ "Vincent Hanquez <vincent.hanquez@iohk.io>" "Nicolas Di Prima <nicolas.diprima@iohk.io>" ];
    src = exclude [ ".git" "target" ] /nix/store/lk795k7bz6d9b9bhax09dhc5wpddmna5-rust-cardano-4403a9f/exe-common/../storage-units;
    dependencies = mapFeatures features ([
      (cratesIO.crates."cryptoxide"."${deps."storage_units"."0.1.0"."cryptoxide"}" deps)
      (cratesIO.crates."rand"."${deps."storage_units"."0.1.0"."rand"}" deps)
    ]);
  };
  features_.storage_units."0.1.0" = deps: f: updateFeatures f (rec {
    cryptoxide."${deps.storage_units."0.1.0".cryptoxide}".default = true;
    rand."${deps.storage_units."0.1.0".rand}".default = true;
    storage_units."0.1.0".default = (f.storage_units."0.1.0".default or true);
  }) [
    (cratesIO.features_.cryptoxide."${deps."storage_units"."0.1.0"."cryptoxide"}" deps)
    (cratesIO.features_.rand."${deps."storage_units"."0.1.0"."rand"}" deps)
  ];



}; in

rec {
  all_crates = crates.crates.all_crates."1.1.1" deps;
  __all = [ (all_crates {}) ];
  deps.aho_corasick."0.6.9" = {
    memchr = "2.1.1";
  };
  deps.all_crates."1.1.1" = {
    cardano = "0.1.0";
    cardano_storage = "0.1.0";
    env_logger = "0.5.13";
    exe_common = "0.1.0";
    generate_msg = "0.1.0";
    log = "0.4.6";
    nom = "3.2.1";
    protocol = "0.1.0";
    rustfbp = "0.3.34";
    storage_units = "0.1.0";
  };
  deps.arrayvec."0.4.8" = {
    nodrop = "0.1.13";
  };
  deps.atty."0.2.11" = {
    termion = "1.5.1";
    libc = "0.2.44";
    winapi = "0.3.6";
  };
  deps.base64."0.9.3" = {
    byteorder = "1.2.7";
    safemem = "0.3.0";
  };
  deps.bitflags."1.0.4" = {};
  deps.byteorder."1.2.7" = {};
  deps.bytes."0.4.11" = {
    byteorder = "1.2.7";
    iovec = "0.1.2";
  };
  deps.cardano."0.1.0" = {
    cbor_event = "1.0.1";
    cryptoxide = "0.1.0";
    serde = "1.0.80";
    serde_derive = "1.0.80";
  };
  deps.cardano_storage."0.1.0" = {
    cardano = "0.1.0";
    cbor_event = "1.0.1";
    log = "0.4.6";
    rand = "0.4.3";
    storage_units = "0.1.0";
  };
  deps.cbor_event."1.0.1" = {};
  deps.cc."1.0.25" = {};
  deps.cfg_if."0.1.6" = {};
  deps.cloudabi."0.0.3" = {
    bitflags = "1.0.4";
  };
  deps.crossbeam_deque."0.6.2" = {
    crossbeam_epoch = "0.6.1";
    crossbeam_utils = "0.6.1";
  };
  deps.crossbeam_epoch."0.6.1" = {
    arrayvec = "0.4.8";
    cfg_if = "0.1.6";
    crossbeam_utils = "0.6.1";
    lazy_static = "1.2.0";
    memoffset = "0.2.1";
    scopeguard = "0.3.3";
  };
  deps.crossbeam_utils."0.6.1" = {
    cfg_if = "0.1.6";
  };
  deps.cryptoxide."0.1.0" = {};
  deps.dtoa."0.4.3" = {};
  deps.env_logger."0.5.13" = {
    atty = "0.2.11";
    humantime = "1.2.0";
    log = "0.4.6";
    regex = "1.0.6";
    termcolor = "1.0.4";
  };
  deps.env_logger."0.6.0" = {
    atty = "0.2.11";
    humantime = "1.2.0";
    log = "0.4.6";
    regex = "1.0.6";
    termcolor = "1.0.4";
  };
  deps.exe_common."0.1.0" = {
    cardano = "0.1.0";
    cardano_storage = "0.1.0";
    cbor_event = "1.0.1";
    futures = "0.1.25";
    hyper = "0.11.27";
    log = "0.4.6";
    protocol = "0.1.0";
    rand = "0.4.3";
    serde = "1.0.80";
    serde_derive = "1.0.80";
    serde_yaml = "0.7.5";
    storage_units = "0.1.0";
    tokio_core = "0.1.17";
  };
  deps.fuchsia_zircon."0.3.3" = {
    bitflags = "1.0.4";
    fuchsia_zircon_sys = "0.3.3";
  };
  deps.fuchsia_zircon_sys."0.3.3" = {};
  deps.futures."0.1.25" = {};
  deps.futures_cpupool."0.1.8" = {
    futures = "0.1.25";
    num_cpus = "1.8.0";
  };
  deps.generate_msg."0.1.0" = {
    syn = "0.12.15";
  };
  deps.httparse."1.3.3" = {};
  deps.humantime."1.2.0" = {
    quick_error = "1.2.2";
  };
  deps.hyper."0.11.27" = {
    base64 = "0.9.3";
    bytes = "0.4.11";
    futures = "0.1.25";
    futures_cpupool = "0.1.8";
    httparse = "1.3.3";
    iovec = "0.1.2";
    language_tags = "0.2.2";
    log = "0.4.6";
    mime = "0.3.12";
    net2 = "0.2.33";
    percent_encoding = "1.0.1";
    relay = "0.1.1";
    time = "0.1.40";
    tokio_core = "0.1.17";
    tokio_io = "0.1.10";
    tokio_proto = "0.1.1";
    tokio_service = "0.1.0";
    unicase = "2.2.0";
    want = "0.0.4";
  };
  deps.iovec."0.1.2" = {
    libc = "0.2.44";
    winapi = "0.2.8";
  };
  deps.kernel32_sys."0.2.2" = {
    winapi = "0.2.8";
    winapi_build = "0.1.1";
  };
  deps.language_tags."0.2.2" = {};
  deps.lazy_static."1.2.0" = {};
  deps.lazycell."1.2.0" = {};
  deps.libc."0.2.44" = {};
  deps.libloading."0.5.0" = {
    cc = "1.0.25";
    winapi = "0.3.6";
  };
  deps.linked_hash_map."0.5.1" = {};
  deps.lock_api."0.1.5" = {
    owning_ref = "0.4.0";
    scopeguard = "0.3.3";
  };
  deps.log."0.3.9" = {
    log = "0.4.6";
  };
  deps.log."0.4.6" = {
    cfg_if = "0.1.6";
  };
  deps.memchr."1.0.2" = {
    libc = "0.2.44";
  };
  deps.memchr."2.1.1" = {
    cfg_if = "0.1.6";
    libc = "0.2.44";
    version_check = "0.1.5";
  };
  deps.memoffset."0.2.1" = {};
  deps.mime."0.3.12" = {
    unicase = "2.2.0";
  };
  deps.mio."0.6.16" = {
    iovec = "0.1.2";
    lazycell = "1.2.0";
    log = "0.4.6";
    net2 = "0.2.33";
    slab = "0.4.1";
    fuchsia_zircon = "0.3.3";
    fuchsia_zircon_sys = "0.3.3";
    libc = "0.2.44";
    kernel32_sys = "0.2.2";
    miow = "0.2.1";
    winapi = "0.2.8";
  };
  deps.mio_uds."0.6.7" = {
    iovec = "0.1.2";
    libc = "0.2.44";
    mio = "0.6.16";
  };
  deps.miow."0.2.1" = {
    kernel32_sys = "0.2.2";
    net2 = "0.2.33";
    winapi = "0.2.8";
    ws2_32_sys = "0.2.1";
  };
  deps.net2."0.2.33" = {
    cfg_if = "0.1.6";
    libc = "0.2.44";
    winapi = "0.3.6";
  };
  deps.nodrop."0.1.13" = {};
  deps.nom."3.2.1" = {
    memchr = "1.0.2";
  };
  deps.num_cpus."1.8.0" = {
    libc = "0.2.44";
  };
  deps.owning_ref."0.4.0" = {
    stable_deref_trait = "1.1.1";
  };
  deps.parking_lot."0.6.4" = {
    lock_api = "0.1.5";
    parking_lot_core = "0.3.1";
  };
  deps.parking_lot_core."0.3.1" = {
    rand = "0.5.5";
    smallvec = "0.6.7";
    rustc_version = "0.2.3";
    libc = "0.2.44";
    winapi = "0.3.6";
  };
  deps.percent_encoding."1.0.1" = {};
  deps.proc_macro2."0.2.3" = {
    unicode_xid = "0.1.0";
  };
  deps.proc_macro2."0.4.24" = {
    unicode_xid = "0.1.0";
  };
  deps.protocol."0.1.0" = {
    cardano = "0.1.0";
    cbor_event = "1.0.1";
    log = "0.4.6";
  };
  deps.quick_error."1.2.2" = {};
  deps.quote."0.4.2" = {
    proc_macro2 = "0.2.3";
  };
  deps.quote."0.6.10" = {
    proc_macro2 = "0.4.24";
  };
  deps.rand."0.3.22" = {
    libc = "0.2.44";
    rand = "0.4.3";
    fuchsia_zircon = "0.3.3";
  };
  deps.rand."0.4.3" = {
    fuchsia_zircon = "0.3.3";
    libc = "0.2.44";
    winapi = "0.3.6";
  };
  deps.rand."0.5.5" = {
    rand_core = "0.2.2";
    cloudabi = "0.0.3";
    fuchsia_zircon = "0.3.3";
    libc = "0.2.44";
    winapi = "0.3.6";
  };
  deps.rand."0.6.1" = {
    rand_chacha = "0.1.0";
    rand_core = "0.3.0";
    rand_hc = "0.1.0";
    rand_isaac = "0.1.1";
    rand_pcg = "0.1.1";
    rand_xorshift = "0.1.0";
    rustc_version = "0.2.3";
    cloudabi = "0.0.3";
    fuchsia_zircon = "0.3.3";
    libc = "0.2.44";
    winapi = "0.3.6";
  };
  deps.rand_chacha."0.1.0" = {
    rand_core = "0.3.0";
    rustc_version = "0.2.3";
  };
  deps.rand_core."0.2.2" = {
    rand_core = "0.3.0";
  };
  deps.rand_core."0.3.0" = {};
  deps.rand_hc."0.1.0" = {
    rand_core = "0.3.0";
  };
  deps.rand_isaac."0.1.1" = {
    rand_core = "0.3.0";
  };
  deps.rand_pcg."0.1.1" = {
    rand_core = "0.3.0";
    rustc_version = "0.2.3";
  };
  deps.rand_xorshift."0.1.0" = {
    rand_core = "0.3.0";
  };
  deps.redox_syscall."0.1.43" = {};
  deps.redox_termios."0.1.1" = {
    redox_syscall = "0.1.43";
  };
  deps.regex."1.0.6" = {
    aho_corasick = "0.6.9";
    memchr = "2.1.1";
    regex_syntax = "0.6.3";
    thread_local = "0.3.6";
    utf8_ranges = "1.0.2";
  };
  deps.regex_syntax."0.6.3" = {
    ucd_util = "0.1.3";
  };
  deps.relay."0.1.1" = {
    futures = "0.1.25";
  };
  deps.rustc_version."0.2.3" = {
    semver = "0.9.0";
  };
  deps.rustfbp."0.3.34" = {
    env_logger = "0.6.0";
    libloading = "0.5.0";
    threadpool = "1.7.1";
  };
  deps.safemem."0.3.0" = {};
  deps.scoped_tls."0.1.2" = {};
  deps.scopeguard."0.3.3" = {};
  deps.semver."0.9.0" = {
    semver_parser = "0.7.0";
  };
  deps.semver_parser."0.7.0" = {};
  deps.serde."1.0.80" = {};
  deps.serde_derive."1.0.80" = {
    proc_macro2 = "0.4.24";
    quote = "0.6.10";
    syn = "0.15.22";
  };
  deps.serde_yaml."0.7.5" = {
    dtoa = "0.4.3";
    linked_hash_map = "0.5.1";
    serde = "1.0.80";
    yaml_rust = "0.4.2";
  };
  deps.slab."0.3.0" = {};
  deps.slab."0.4.1" = {};
  deps.smallvec."0.2.1" = {};
  deps.smallvec."0.6.7" = {
    unreachable = "1.0.0";
  };
  deps.stable_deref_trait."1.1.1" = {};
  deps.storage_units."0.1.0" = {
    cryptoxide = "0.1.0";
    rand = "0.5.5";
  };
  deps.syn."0.12.15" = {
    proc_macro2 = "0.2.3";
    quote = "0.4.2";
    unicode_xid = "0.1.0";
  };
  deps.syn."0.15.22" = {
    proc_macro2 = "0.4.24";
    quote = "0.6.10";
    unicode_xid = "0.1.0";
  };
  deps.take."0.1.0" = {};
  deps.termcolor."1.0.4" = {
    wincolor = "1.0.1";
  };
  deps.termion."1.5.1" = {
    libc = "0.2.44";
    redox_syscall = "0.1.43";
    redox_termios = "0.1.1";
  };
  deps.thread_local."0.3.6" = {
    lazy_static = "1.2.0";
  };
  deps.threadpool."1.7.1" = {
    num_cpus = "1.8.0";
  };
  deps.time."0.1.40" = {
    libc = "0.2.44";
    redox_syscall = "0.1.43";
    winapi = "0.3.6";
  };
  deps.tokio."0.1.13" = {
    bytes = "0.4.11";
    futures = "0.1.25";
    mio = "0.6.16";
    num_cpus = "1.8.0";
    tokio_codec = "0.1.1";
    tokio_current_thread = "0.1.4";
    tokio_executor = "0.1.5";
    tokio_fs = "0.1.4";
    tokio_io = "0.1.10";
    tokio_reactor = "0.1.7";
    tokio_tcp = "0.1.2";
    tokio_threadpool = "0.1.9";
    tokio_timer = "0.2.8";
    tokio_udp = "0.1.3";
    tokio_uds = "0.2.4";
  };
  deps.tokio_codec."0.1.1" = {
    bytes = "0.4.11";
    futures = "0.1.25";
    tokio_io = "0.1.10";
  };
  deps.tokio_core."0.1.17" = {
    bytes = "0.4.11";
    futures = "0.1.25";
    iovec = "0.1.2";
    log = "0.4.6";
    mio = "0.6.16";
    scoped_tls = "0.1.2";
    tokio = "0.1.13";
    tokio_executor = "0.1.5";
    tokio_io = "0.1.10";
    tokio_reactor = "0.1.7";
    tokio_timer = "0.2.8";
  };
  deps.tokio_current_thread."0.1.4" = {
    futures = "0.1.25";
    tokio_executor = "0.1.5";
  };
  deps.tokio_executor."0.1.5" = {
    futures = "0.1.25";
  };
  deps.tokio_fs."0.1.4" = {
    futures = "0.1.25";
    tokio_io = "0.1.10";
    tokio_threadpool = "0.1.9";
  };
  deps.tokio_io."0.1.10" = {
    bytes = "0.4.11";
    futures = "0.1.25";
    log = "0.4.6";
  };
  deps.tokio_proto."0.1.1" = {
    futures = "0.1.25";
    log = "0.3.9";
    net2 = "0.2.33";
    rand = "0.3.22";
    slab = "0.3.0";
    smallvec = "0.2.1";
    take = "0.1.0";
    tokio_core = "0.1.17";
    tokio_io = "0.1.10";
    tokio_service = "0.1.0";
  };
  deps.tokio_reactor."0.1.7" = {
    crossbeam_utils = "0.6.1";
    futures = "0.1.25";
    lazy_static = "1.2.0";
    log = "0.4.6";
    mio = "0.6.16";
    num_cpus = "1.8.0";
    parking_lot = "0.6.4";
    slab = "0.4.1";
    tokio_executor = "0.1.5";
    tokio_io = "0.1.10";
  };
  deps.tokio_service."0.1.0" = {
    futures = "0.1.25";
  };
  deps.tokio_tcp."0.1.2" = {
    bytes = "0.4.11";
    futures = "0.1.25";
    iovec = "0.1.2";
    mio = "0.6.16";
    tokio_io = "0.1.10";
    tokio_reactor = "0.1.7";
  };
  deps.tokio_threadpool."0.1.9" = {
    crossbeam_deque = "0.6.2";
    crossbeam_utils = "0.6.1";
    futures = "0.1.25";
    log = "0.4.6";
    num_cpus = "1.8.0";
    rand = "0.6.1";
    tokio_executor = "0.1.5";
  };
  deps.tokio_timer."0.2.8" = {
    crossbeam_utils = "0.6.1";
    futures = "0.1.25";
    slab = "0.4.1";
    tokio_executor = "0.1.5";
  };
  deps.tokio_udp."0.1.3" = {
    bytes = "0.4.11";
    futures = "0.1.25";
    log = "0.4.6";
    mio = "0.6.16";
    tokio_codec = "0.1.1";
    tokio_io = "0.1.10";
    tokio_reactor = "0.1.7";
  };
  deps.tokio_uds."0.2.4" = {
    bytes = "0.4.11";
    futures = "0.1.25";
    iovec = "0.1.2";
    libc = "0.2.44";
    log = "0.4.6";
    mio = "0.6.16";
    mio_uds = "0.6.7";
    tokio_codec = "0.1.1";
    tokio_io = "0.1.10";
    tokio_reactor = "0.1.7";
  };
  deps.try_lock."0.1.0" = {};
  deps.ucd_util."0.1.3" = {};
  deps.unicase."2.2.0" = {
    version_check = "0.1.5";
  };
  deps.unicode_xid."0.1.0" = {};
  deps.unreachable."1.0.0" = {
    void = "1.0.2";
  };
  deps.utf8_ranges."1.0.2" = {};
  deps.version_check."0.1.5" = {};
  deps.void."1.0.2" = {};
  deps.want."0.0.4" = {
    futures = "0.1.25";
    log = "0.4.6";
    try_lock = "0.1.0";
  };
  deps.winapi."0.2.8" = {};
  deps.winapi."0.3.6" = {
    winapi_i686_pc_windows_gnu = "0.4.0";
    winapi_x86_64_pc_windows_gnu = "0.4.0";
  };
  deps.winapi_build."0.1.1" = {};
  deps.winapi_i686_pc_windows_gnu."0.4.0" = {};
  deps.winapi_util."0.1.1" = {
    winapi = "0.3.6";
  };
  deps.winapi_x86_64_pc_windows_gnu."0.4.0" = {};
  deps.wincolor."1.0.1" = {
    winapi = "0.3.6";
    winapi_util = "0.1.1";
  };
  deps.ws2_32_sys."0.2.1" = {
    winapi = "0.2.8";
    winapi_build = "0.1.1";
  };
  deps.yaml_rust."0.4.2" = {
    linked_hash_map = "0.5.1";
  };
}
